name: Build Contribution Graph GIF

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch
          git checkout contr-graph-gif
          git config user.name "Ethan Uppal" 
          git config user.email "113849268+ethanuppal@users.noreply.github.com"
          git add -A .
          git commit -m "Generated 3D Contribution Graph GIF"
          git push origin contr-graph-gif
